module.exports = [
    {
        town: "Rawang",
        state: "Selangor",
        latitude: 3.3584,
        longitude: 101.5766,
    },
    {
        town: "Kuala Selangor",
        state: "Selangor",
        latitude: 3.3496,
        longitude: 101.2532,
    },
    {
        town: "Tanjung Tokong",
        state: "Penang",
        latitude: 5.4515,
        longitude: 100.3054,
    },
    {
        town: "Tasek Gelugor",
        state: "Penang",
        latitude: 5.4973,
        longitude: 100.4708,
    },
    {
        town: "Bukit Mertajam",
        state: "Penang",
        latitude: 5.3639,
        longitude: 100.4617,
    },
    {
        town: "Nibong Tebal",
        state: "Penang",
        latitude: 5.1741,
        longitude: 100.4851,
    },
    {
        town: "Simpang Ampat",
        state: "Penang",
        latitude: 5.2753,
        longitude: 100.4867,
    },
    {
        town: "Sungai Petani",
        state: "Kedah",
        latitude: 5.6470,
        longitude: 100.4877,
    },
    {
        town: "Alor Setar",
        state: "Kedah",
        latitude: 6.1270,
        longitude: 100.3673,
    },
    {
        town: "Jitra",
        state: "Kedah",
        latitude: 6.2649,
        longitude: 100.4227,
    },
    {
        town: "Kuala Perlis",
        state: "Perlis",
        latitude: 6.4446,
        longitude: 100.1978,
    },
    {
        town: "Kangar",
        state: "Perlis",
        latitude: 6.4498,
        longitude: 100.1955,
    },
    {
        town: "Arau",
        state: "Perlis",
        latitude: 6.3976,
        longitude: 100.2649,
    },
    {
        town: "Kuala Kangsar",
        state: "Perak",
        latitude: 4.7744,
        longitude: 100.9357,
    },
    {
        town: "Ipoh",
        state: "Perak",
        latitude: 4.5975,
        longitude: 101.0901,
    },
    {
        town: "Teluk Intan",
        state: "Perak",
        latitude: 4.0285,
        longitude: 101.0201,
    },
    {
        town: "Sitiawan",
        state: "Perak",
        latitude: 4.2159,
        longitude: 100.6917,
    },
    {
        town: "Seremban",
        state: "Negeri Sembilan",
        latitude: 2.7297,
        longitude: 101.9381,
    },
    {
        town: "Port Dickson",
        state: "Negeri Sembilan",
        latitude: 2.5222,
        longitude: 101.7969,
    },
    {
        town: "Nilai",
        state: "Negeri Sembilan",
        latitude: 2.8134,
        longitude: 101.7979,
    },
    {
        town: "Bahau",
        state: "Negeri Sembilan",
        latitude: 2.8062,
        longitude: 102.4611,
    },
    {
        town: "Batu Pahat",
        state: "Johor",
        latitude: 1.8500,
        longitude: 102.9333,
    },
    {
        town: "Muar",
        state: "Johor",
        latitude: 2.0442,
        longitude: 102.5686,
    },
    {
        town: "Kulai",
        state: "Johor",
        latitude: 1.6686,
        longitude: 103.6031,
    },
    {
        town: "Kluang",
        state: "Johor",
        latitude: 2.0418,
        longitude: 103.3210,
    },
    {
        town: "Segamat",
        state: "Johor",
        latitude: 2.5003,
        longitude: 102.8165,
    },
    {
        town: "Pasir Gudang",
        state: "Johor",
        latitude: 1.4586,
        longitude: 103.8820,
    },
    {
        town: "Tangkak",
        state: "Johor",
        latitude: 2.2630,
        longitude: 102.5415,
    },
    {
        town: "Kota Tinggi",
        state: "Johor",
        latitude: 1.7320,
        longitude: 103.9043,
    },
    {
        town: "Pontian Kechil",
        state: "Johor",
        latitude: 1.4867,
        longitude: 103.3931,
    },
    {
        town: "Yong Peng",
        state: "Johor",
        latitude: 2.0155,
        longitude: 103.0649,
    },
    {
        town: "Tampin",
        state: "Negeri Sembilan",
        latitude: 2.4759,
        longitude: 102.2359,
    },
    {
        town: "Melaka",
        state: "Malacca",
        latitude: 2.2057,
        longitude: 102.2565,
    },
    {
        town: "Batu Berendam",
        state: "Malacca",
        latitude: 2.2493,
        longitude: 102.2714,
    },
];
